version: "3.3"
services:
  ph803w2mqtt:
    image: cellerich/ph803w2mqtt:0.0.4
    restart: always
    environment:
      - PH803W_IP=192.168.0.xx
      - MQTT_IP=192.168.0.yyy
      - MQTT_user=user
      - MQTT_pass=secret
      - MQTT_topic=poolphdata
      - MQTT_clientID=ph803w2mqtt
      - LOGGING=off

